### ISSUE TITLE
Send parameters to the html file?

### ISSUE THREAD

**Issue by brunogenaro** [jdanthinne/tiBrowser#4]
Is there any way to send parameters to the HTML file from the controller?

It looks like Titanium has a method evalJS for the webView object. How can I adapt it to work properly on tiBrowser?

**Comment by brunogenaro** [comment]
Just created this functionality. I've opened a Pull request, fell free to review and give your feedback.

**Comment by jdanthinne** [comment]
Wouldn't it be safer to test if the _loadExternalData_ javascript function exists before launching it?

**Comment by brunogenaro** [comment]
You are right! Just added the conditional. Thanks

**Comment by jdanthinne** [comment]
Seems ok for me. Just merged.
